#!/usr/bin/env python3
"""Inventory/verify/package explicit scientific inputs. Never runs numerical code."""
import argparse,hashlib,json,re,subprocess,tarfile,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DOC=ROOT/'docs/independent_reproduction_v1'
ROOTS=['data','results/final_reproduction/production/accuracy','results/final_reproduction/resolved_accuracy_v1',
 'results/controlled_study_2026/float64_v2/production/baseline','results/controlled_study_2026/float64_v2/dataset_roots','results/controlled_study_2026/float64_v2/lag_datasets','results/controlled_study_2026/float64_v2_validation',
 'results/capacity_regime_ex8_v1','results/capacity_regime_ex8_v2','results/capacity_regime_ex8_final_h_v1',
 'results/ex8_h_lambda_drift_v1','results/arff_fixed_basis_ridge_diagnostic_v1','results/arff_B_ridge_intervention_v1','results/arff_resampling_isolation_v1',
 'results/arff_drift_K_mechanism_diagnostic_phase2_final_v1','results/arff_ridge_noise_scaling_v1',
 'results/controlled_study_2026/float64_v2/hybrid_jointmlp_arff','results/controlled_study_2026/float64_v2/oracle_component_swap',
 'results/final_ex8_publication_bundle/summaries','results/conservative_manuscript_revision_v1/archive_inputs','results/conservative_manuscript_revision_v1/evaluation']
EXTRA=['results/final_reproduction/production_manifest.v5.json','results/final_reproduction/production_manifest.adam_v1.json','results/final_reproduction/production_manifest.arff_v1.json',
 'results/controlled_study_2026/float64_v2/manifest.json','results/controlled_study_2026/float64_v2/registration_sha256.json','results/controlled_study_2026/float64_v2/STUDY_PLAN.md','results/controlled_study_2026/float64_v2/campaigns/baseline/plan.json',
 'results/controlled_study_2026/preflight/matched_noise_precision_gpu.npz']
SUFFIX={'.npz','.npy','.json','.csv','.py','.md','.sha256'}
DENY={'git_status','git_diff','launch','active_started','controller_started','reservation','PERSISTENCE_CHECK','gpu_memory','environment'}
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(8*1024*1024),b''):h.update(b)
 return h.hexdigest()
def private_reference(p):
 t=str(p).lower()
 return any(x in t for x in ['/external/','historical_manuscript_layout','scientific_review_20260909/historical_transcription','scientific_review_20260909/report.md','manuscript_reconciliation','feedback','attachments'])
def acceptable(p):
 return p.name not in {'package_independent_reproduction.py','reproduction_route.py','reproduction_generate.py','evaluate_reproduction_checkpoint.py'} and not private_reference(p) and p.stem!='ex4' and p.is_file() and p.suffix in SUFFIX and not any(x in p.parts for x in ['__pycache__','ex4']) and not any(p.name.startswith(x) for x in DENY)
def local(s):
 # Original absolute provenance keys are mapped only for locating files, never rewritten.
 marker='SDE_ARFF_2026/'
 if marker in s:s=s.split(marker,1)[1]
 p=Path(s)
 if p.is_absolute() or '..' in p.parts:return None
 if not p.parts or p.parts[0] not in ['results','data','scripts','src','GPU']:return None
 return ROOT/p

def role(rel):
 if rel.startswith('data/') or '/dataset_roots/' in rel or '/data/' in rel:return 'data/split input (essential to exact fit and evaluation)'
 if '/source' in rel or rel.endswith('.py'):return 'source/configuration (essential when referenced by hash)'
 if rel.endswith(('.npz','.npy')):return 'checkpoint or recorded random/data array (exact evaluation; optional for fresh fitting unless shared diagnostic input)'
 if rel.endswith('.csv'):return 'archived metrics/history (figure rebuild; generated by evaluation)'
 return 'protocol/provenance/validation (version and selection identity)'
def recipe(rel):
 if rel.startswith(('src/','scripts/','GPU/')) or '/sources/' in rel or '/source_snapshot/' in rel or rel.endswith('.py'):return 'source: restore exact shipped bytes; not numerically generated'
 if rel.endswith(('.txt','.patch','.pdf','.png')):return 'optional archived provenance/plot/log; original command recorded in parent study, not required scientific input'
 if rel.startswith('data/'):
  return 'data-generation: ROUTES.md original generator then ex6 label correction or ex8 float64 correction as indicated by filename; restore for exact container hash'
 if '/stream_' in rel:return 'resampling RNG_SPEC.json and study.py:preflight; restore exact recorded stream for pairing'
 if 'arff_' in rel and 'capacity_regime' not in rel:return 'surrogate: registered shared data and A/B/C parent fits -> fixed-basis/adaptive-ridge/resampling routes; restore for exact checkpoint evaluation'
 if 'ex8_h_lambda' in rel:return 'lag-ridge route at encoded h/lambda/seed; summaries generated from all arms'
 if '/production/' in rel:return 'training route selected by parent frozen campaign plan and path experiment/method/K/N/h/seed; checkpoint selection/evaluation are inside runner'
 if '/dataset_roots/' in rel or '/lag_datasets/' in rel or '/data/' in rel:return 'data-generation chain in ROUTES.md; archived coupled parent, block PRNG recipe and splits required'
 if 'conservative_manuscript' in rel:return 'archived rebuild route; coefficient grids require saved-model reconstruction gate'
 return 'generated manifest/metrics/provenance: parent study source and frozen plan in bundle; restore identity, regeneration records new execution provenance'

def inventory():
 files={Path(folder)/name for d in ROOTS for folder,_,names in os.walk(ROOT/d,followlinks=True) for name in names if acceptable(Path(folder)/name)}|{ROOT/x for x in EXTRA}
 tracked=set(subprocess.check_output(['git','ls-files'],cwd=ROOT,text=True).splitlines())
 # Include tracked numerical sources; closure below also captures untracked authenticated sources.
 files|={ROOT/p for p in tracked if p.startswith(('src/','scripts/','GPU/lib/')) and p.endswith('.py')}
 scanned=set();missing=set();dependencies={}
 while todo:=files-scanned:
  for p in todo:
   scanned.add(p)
   if not p.is_file():missing.add(str(p.relative_to(ROOT)));continue
   if p.suffix!='.json':continue
   try:obj=json.loads(p.read_text())
   except (ValueError,UnicodeError):continue
   def visit(v):
    if isinstance(v,dict):
     for k,x in v.items():
      if isinstance(x,str) and re.fullmatch('[0-9a-f]{64}',x):
       q=local(k)
       if q is None and not Path(k).is_absolute() and '..' not in Path(k).parts and (p.parent/k).is_file():q=p.parent/k
       if q:
        dependencies.setdefault(str(q.relative_to(ROOT)),set()).add(str(p.relative_to(ROOT)))
        if q.is_file() and not private_reference(q):files.add(q)
        elif not q.is_file():missing.add(str(q.relative_to(ROOT)))
      visit(x)
    elif isinstance(v,list):
     for x in v:visit(x)
   visit(obj)
 records=[];hashes={};issues=[]
 for p in sorted(files):
  if not p.is_file():continue
  rel=str(p.relative_to(ROOT));h=sha(p);size=p.stat().st_size
  # No external symlink target is published blindly.
  if p.is_symlink() and not p.resolve().is_relative_to(ROOT):raise RuntimeError('External symlink: '+rel)
  if p.suffix in {'.py','.json','.md','.csv','.txt','.patch'}:
   t=p.read_text(errors='replace')
   if re.search(r'BEGIN (?:RSA |OPENSSH )?PRIVATE KEY|\b(?:ghp_|github_pat_|sk-)[A-Za-z0-9_]{20,}',t):raise RuntimeError('Secret-like content: '+rel)
  records.append(dict(path=rel,sha256=h,bytes=size,availability='tracked' if rel in tracked else 'local-only; external bundle',purpose=role(rel),regeneration=recipe(rel),required_by=sorted(dependencies.get(rel,[]))))
  hashes[h]=size
 result=dict(version='independent_reproduction_v1',source_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),files=records,missing_referenced_files=sorted(missing),excluded_private_provenance='External manuscript snapshots, historical manuscript text/transcription and private feedback are not numerical inputs; their archived preservation hashes remain in provenance but payloads are excluded.',logical_bytes=sum(x['bytes'] for x in records),unique_content_bytes=sum(hashes.values()),public_download=None,independent_backup='not verified; same-server backup is not independent')
 DOC.mkdir(exist_ok=True);(DOC/'artifact_manifest.json').write_text(json.dumps(result,indent=2)+'\n')
 print(json.dumps({k:v for k,v in result.items() if k!='files'},indent=2));print('files',len(records))
def main():
 ap=argparse.ArgumentParser();ap.add_argument('mode',choices=['inventory','verify','bundle','verify-tar']);ap.add_argument('--root',type=Path,default=ROOT);ap.add_argument('--manifest',type=Path,default=DOC/'artifact_manifest.json');ap.add_argument('--output',type=Path);ap.add_argument('--archive',type=Path);a=ap.parse_args()
 if a.mode=='inventory':inventory();return
 m=json.loads(a.manifest.read_text());bad=[]
 if a.mode=='verify-tar':
  if not a.archive:ap.error('--archive required')
  expected={r['path']:r for r in m['files']};seen={}
  with tarfile.open(a.archive,'r:') as tar:
   for member in tar:
    name=member.name
    if name not in expected or name in seen or Path(name).is_absolute() or '..' in Path(name).parts:raise SystemExit('Unexpected archive member: '+name)
    if member.islnk():
     if member.linkname not in seen:raise SystemExit('Invalid hardlink: '+name)
     h,size=seen[member.linkname]
    elif member.isfile():
     hobj=hashlib.sha256();size=0
     with tar.extractfile(member) as f:
      for b in iter(lambda:f.read(8*1024*1024),b''):hobj.update(b);size+=len(b)
     h=hobj.hexdigest()
    else:raise SystemExit('Unsupported archive member: '+name)
    if (h,size)!=(expected[name]['sha256'],expected[name]['bytes']):raise SystemExit('Archive payload mismatch: '+name)
    seen[name]=(h,size)
  if set(seen)!=set(expected):raise SystemExit('Archive has missing members')
  print('Verified tar payload:',len(seen),'files');return
 for r in m['files']:
  p=a.root/r['path']
  if not p.is_file() or p.stat().st_size!=r['bytes'] or sha(p)!=r['sha256']:bad.append(r['path'])
 if bad:raise SystemExit('Missing or mismatched files:\n'+'\n'.join(bad))
 print('Verified',len(m['files']),'files')
 if a.mode=='bundle':
  if not a.output:ap.error('--output required')
  # Archive is flat repository layout; identical content stored once as tar hardlinks.
  seen={}
  with a.output.open('xb') as out,tarfile.open(fileobj=out,mode='w') as tar:
   for r in m['files']:
    p=a.root/r['path'];info=tar.gettarinfo(str(p),arcname=r['path']);info.uid=info.gid=0;info.uname=info.gname='';info.mtime=0
    if r['sha256'] in seen:
     info.type=tarfile.LNKTYPE;info.linkname=seen[r['sha256']];info.size=0;tar.addfile(info)
    else:
     info.type=tarfile.REGTYPE;info.linkname='';info.size=r['bytes']
     with p.open('rb') as f:tar.addfile(info,f)
     seen[r['sha256']]=r['path']
  print('Bundle',a.output.stat().st_size,'bytes; SHA256',sha(a.output))
if __name__=='__main__':main()
